### ISSUE TITLE
MA3 Patch, results in broken external player

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/animeplugin3#15]
**Reported by andyieg.andreas, Mar 3, 2014**

**What steps will reproduce the problem?**
Replace the Anime.dll, with the version from the patch.

I guess this patch is only for certain users, since it breaks my setup. So a more descriptive text for the patch would be nice.

**Comment by ElementalCrisis** [comment]
I'm going to close this as it's was for an older version, if the problem is still present then comment in this thread.
