### ISSUE TITLE
Group filter does not show all groups

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/animeplugin3#20]
http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-71#post-1112702

With the beta (3.4.2.8) I observe a mismatch for identified number of groups between the plugin and JMM Desktop-
While the correct total number of groups are identfied in JMMDesktop, only a subset is listed and shown in the plugin.

I observe the behaviour for some time now with the betas, but couldn't find a cause.
For a custom filter (all unviewed animes since a specific date) shows also only a subset of the actual hits, but this happens to be the same in the JMMDesktop & the plugin

after some time the list is corrected shown in the plugin.

So far I assumed that it is the server itself, but since I see a difference in behaviour, I am not sure anymor.

Note: my files are on two servers and linked as shares via UNC path (\\server\share) and are sometmes not present at startup

As this has never happened with the release versions one can only guess as related to one of the modifications

Both Group Filters show after start-up only a subset of hits. (for the shown below it should be ~46 hits)
The filters were working fine in the release versions; so behaviour started with the betas.

While I was typing this the number of hits increases (see second pic)

Forcing full import generates some hundred activities and some hours later you will have eventually all matching groups shown

Cheers

Addendum (03.01.15):
Seems like there is also a discrepancy for identified groups in the "ALL" category between MP plugin & JMM Desktop:
While JMM Desktop is showing correctly 598 groups, the MP Plugin identifies only 32 groups
"2012-2014(ALL)": 28 for JMM Desktop & MP Plugin
"2012-2014(unseen)": 10 for JMM Desktop & MP Plugin

**Comment by yhoogi** [comment]
Some screenshots to show the situation:
![pic3t](https://cloud.githubusercontent.com/assets/10504005/5709235/73f1b1de-9a98-11e4-8b9e-4ad78c6332d5.png)
![pic4t](https://cloud.githubusercontent.com/assets/10504005/5709234/73f13a10-9a98-11e4-8d5d-498fbd93ce07.png)

Normally the number of filtered items should be:
2013-2015(all): 134
2013-2015(Unseen): 32

they gradually increase over time up to nominal figures

**Comment by jmediamanager** [comment]
@yhoogi, ok I have tried on my test machines (sql server) and can't reproduce the issue.

I will setup a mysql database to see if it is related to that instead.

Could you please let me know what version of MySQL you are running, and what operating system you have it on.

Alternatively you can give me a copy of your database, and I can test using that as well/

**Comment by yhoogi** [comment]
first quick response:
MySQL 5.6.22 (updated yesterday; formerly it was 5.6.17)
Windows 8.1

**Comment by jmediamanager** [comment]
Great, thanks

**Comment by yhoogi** [comment]
I can't upload the DB here
I will give it to you in the forum as direct chat
PW:
MYAnimeSQL

**Comment by yhoogi** [comment]
Info on db location in forum chat

**Comment by AreFinstad** [comment]
you can just uploaded it to any file host like google drive, mega.co.nz, jottadrive, dropbox or whatever and post a link here. not that hard to share a file with someone even if the site does not support it, there really should be no need to post files there that way away from the issue and such.

**Comment by jmediamanager** [comment]
Fix Available in 3.4.2.10

Basically you were missing TvDB information for one series
http://thetvdb.com/?tab=series&id=264527

If you force the update for this series now it should also solve the issue for you
The code can now handle missing information and continue on
