### ISSUE TITLE
MA3 will crash MediaPortal after viewing an unwatched episode, 'SuicideForm' error

### ISSUE THREAD

**Issue by MasterWormy** [japanesemediamanager/animeplugin3#24]
This bug has been pestering me since I updated to MP 1.7.1 about May 2014. It only happens when MediaPortal's Dynamic Refresh Rate changer is enabled. But it was all working fine together in MP 1.6 or whatever I had before 1.7.1.

This bug has several ways of rearing its head but for now the simplest to explain is what I'll call 'Type A'

Description:
Type A:
1) Play any episode marked 'unwatched' via MA3 plugin.
2) Let the episode end (or by skipping to the end, or by stopping at any point).
3) Start any other episode of anything via MA3.
System switches to playback for a split second before returning to episode selection, error appears on screen:
![ma3crash a](https://cloud.githubusercontent.com/assets/10624542/5885833/20dd74bc-a3ce-11e4-9430-d82aab88b2f4.jpg)
4) Window focus should be on the error window, so you can use keyboard or remote to select Quit, which will bring up a 'MediaPortal has crashed, close program, etc.' window. select Close Program and proceed to restart MP, etc. 

Complete Logs for Type A available here: https://www.dropbox.com/s/iilfy70bot8anpn/MA3CrashLogs_TypeA%2824-01-15%29.zip?dl=0

Will edit this post later with Type B and C logs and stuff later. 

Edit: Cannot repro what was going to be Type B anymore... dunno.

**Comment by maxpiva** [comment]
Latest version will not exhibit this behavior since the hacky hook is removed.
